# Generated by Django 5.2.3 on 2026-04-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtechapp', '0007_adminuser_eventcategory_eventregistration_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.BooleanField(default=False)),
            ],
        ),
    ]
